# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

In [3]:
np.version

<module 'numpy.version' from 'D:\\ana\\lib\\site-packages\\numpy\\version.py'>

## Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).


### Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
l = range(1000)
%timeit [i**2 for i in l]

1.1 ms ± 50.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
import numpy as np
a = np.arange(1000)
%timeit a**2

5.12 µs ± 330 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
#help(np.array)

In [7]:
my_list = [1,2,3,4,5,6,4,3,2,2]
my_list

[1, 2, 3, 4, 5, 6, 4, 3, 2, 2]

In [9]:
arr=np.array(my_list) #creating 1-d array from list

In [10]:
print(arr)
np.alen(arr) #returns length

[1 2 3 4 5 6 4 3 2 2]


10

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 4, 3, 2, 2])

In [12]:
arr.shape=2,5

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [6, 4, 3, 2, 2]])

In [14]:
arr.shape

(2, 5)

In [15]:
arr.ndim

2

In [16]:
my_matrix = [[1,2,3,4],[4,5,6,2],[7,8,9,2]]
my_matrix

[[1, 2, 3, 4], [4, 5, 6, 2], [7, 8, 9, 2]]

In [17]:
a=np.array(my_matrix)

In [18]:
print(a)

[[1 2 3 4]
 [4 5 6 2]
 [7 8 9 2]]


In [19]:
a.ndim

2

In [20]:
a.shape

(3, 4)

In [21]:
np.alen(a)

3

In [ ]:
a.ndim #checking the dimension of array

In [22]:
a.size

12

In [23]:
a.itemsize

4

In [24]:
a = np.array([2,3,4])

In [25]:
a = np.array(1,2,3,4,5)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [26]:
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [27]:
b = np.array([(1.5,2,3), (4,5,6)]) #sequence of tuples inside list

In [28]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [29]:
b.shape

(2, 3)

In [30]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [31]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

### arange

Return evenly spaced values within a given interval.

In [32]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [37]:
a = np.arange(20).reshape(2,5,2)

In [38]:
a.shape

(2, 5, 2)

In [39]:
a.ndim

3

In [40]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [41]:
a.dtype.name

'int32'

In [42]:
a.itemsize

4

In [43]:
a.size #total array size

20

In [44]:
type(a) # checking type of array

numpy.ndarray

In [ ]:
a

In [45]:
b = np.array([6, 7, 8])

In [46]:
c = np.arange(24).reshape(3,2,4)  #3d array

In [47]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
np.arange( 0, 2, 0.3 )          # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

When arange is used with floating point arguments, it is generally not possible 
to predict the number of elements obtained, due to the finite floating point 
precision. For this reason, it is usually better to use the function linspace 
that receives as an argument the number of elements that we want, 
instead of the step:

In [49]:
from numpy import pi
np.linspace( 0, 7)

array([ 0.        ,  0.14285714,  0.28571429,  0.42857143,  0.57142857,
        0.71428571,  0.85714286,  1.        ,  1.14285714,  1.28571429,
        1.42857143,  1.57142857,  1.71428571,  1.85714286,  2.        ,
        2.14285714,  2.28571429,  2.42857143,  2.57142857,  2.71428571,
        2.85714286,  3.        ,  3.14285714,  3.28571429,  3.42857143,
        3.57142857,  3.71428571,  3.85714286,  4.        ,  4.14285714,
        4.28571429,  4.42857143,  4.57142857,  4.71428571,  4.85714286,
        5.        ,  5.14285714,  5.28571429,  5.42857143,  5.57142857,
        5.71428571,  5.85714286,  6.        ,  6.14285714,  6.28571429,
        6.42857143,  6.57142857,  6.71428571,  6.85714286,  7.        ])

In [50]:
x = np.linspace( 0, 15,3)  #default length is 50      
# useful to evaluate function at lots of points
x

array([  0. ,   7.5,  15. ])

In [51]:
len(x)

3

In [52]:
f = np.sin(x)

In [53]:
f

array([ 0.        ,  0.93799998,  0.65028784])

### zeros and ones

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [54]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [55]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [93]:
np.ones( (2,3,4), dtype=np.int32 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [64]:
np.empty( (3,4) )

array([[  1.44275648e-312,   3.16202013e-322,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   6.23081720e+174,   5.75087871e-066,
          1.20908971e+161],
       [  3.99455271e+175,   4.22479021e-062,   4.99995000e+174,
          2.23296398e-052]])

In [63]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

### linspace
Return evenly spaced numbers over a specified interval.

In [65]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [66]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [67]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [68]:
np.random.rand(3)

array([ 0.13449057,  0.15860352,  0.78882962])

In [69]:
np.random.rand(5,5)

array([[ 0.89260655,  0.15748959,  0.94218412,  0.7962953 ,  0.56430483],
       [ 0.86150643,  0.39059267,  0.70351414,  0.71624437,  0.82014913],
       [ 0.83317791,  0.66483002,  0.5543328 ,  0.15056796,  0.71901131],
       [ 0.27102817,  0.87367902,  0.78881854,  0.45772318,  0.21188448],
       [ 0.98070588,  0.1389097 ,  0.22994565,  0.72600427,  0.09092944]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [70]:
np.random.randn(4)

array([ 0.30755518,  0.57824532,  0.23294551,  0.57998726])

In [71]:
np.random.randn(5,5)

array([[-0.3021833 , -0.41880776,  1.33199238, -0.73073807, -1.19801129],
       [ 0.79787823, -0.20942987,  2.93705703,  0.71886893, -1.88461216],
       [ 1.08597327, -0.64732325, -0.97047356, -0.10016207, -1.15557147],
       [-0.11991131,  1.97125941,  0.74751163,  0.58315286,  1.40164391],
       [-0.67329727,  0.87647356,  1.73085076,  1.15927413,  0.42018942]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [72]:
np.random.randint(1,100)

61

In [73]:
np.random.randint(1,100,10)

array([36, 99, 53,  7, 75, 24, 32, 74, 18, 34])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [79]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
ranarr

array([12, 46,  8, 19, 25, 16, 37, 24, 43, 27])

## Reshape
Returns an array containing the same data with a new shape.

In [77]:
arr
arr.reshape(5,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 3],
       [2, 2]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [82]:
ranarr

array([12, 46,  8, 19, 25, 16, 37, 24, 43, 27])

In [83]:
ranarr.max() #returns maximum value

46

In [84]:
ranarr.argmax() #returns the index of the maximum value

1

In [85]:
ranarr.min() #returns the minimum value

8

In [86]:
ranarr.argmin() #returns the index of the minimum value

2

## Shape

Shape is an attribute that arrays have (not a method):

In [87]:
# Vector
arr.shape

(25,)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [90]:
arr.reshape(1,25).shape

(1, 25)

In [91]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

In [92]:
arr.dtype

dtype('int32')