While executing the functions, some of them return a copy of the input array, while some return the view. When the contents are physically stored in another location, it is called Copy. If on the other hand, a different view of the same memory content is provided, we call it as View.

Simple assignments do not make the copy of array object. Instead, it uses the same id() of the original array to access it. The id() returns a universal identifier of Python object, similar to the pointer in C.

In [1]:
import numpy as np 

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
b = a 

In [5]:
b

array([0, 1, 2, 3, 4, 5])

In [6]:
id(a)==id(b)

True

In [7]:
b.shape = 3,2 

In [8]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
b[0,0]=4

In [11]:
a

array([[4, 1],
       [2, 3],
       [4, 5]])

### View or Shallow Copy

NumPy has ndarray.view() method which is a new array object that looks at the same data of the original array. Unlike the earlier case, change in dimensions of the new array doesn’t change dimensions of the original.

In [12]:
import numpy as np 

In [13]:
a = np.arange(6).reshape(3,2)

In [14]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
b=a.view()

In [16]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
id(a)==id(b)

False

In [18]:
b is a

False

In [19]:
b.shape = 2,3 

In [20]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b[0,0]=9

In [23]:
a

array([[9, 1],
       [2, 3],
       [4, 5]])

### Deep Copy

The ndarray.copy() function creates a deep copy. It is a complete copy of the array and its data, and doesn’t share with the original array.

In [24]:
import numpy as np 
a = np.array([[10,10], [2,3], [4,5]]) 

In [25]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [26]:
b=a.copy()

In [27]:
b

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [28]:
b is a

False

In [29]:
id(a)==id(b)

False

In [30]:
b[0,0] = 100

In [31]:
id(a)==id(b)

False

In [32]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

In [33]:
b

array([[100,  10],
       [  2,   3],
       [  4,   5]])

In [34]:
b.shape=2,3

In [35]:
a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])