# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [1]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

In [2]:
c = a-b
c

array([20, 29, 38, 47])

In [3]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [4]:
a[a<35]

array([20, 30])

Unlike in many matrix languages, the product operator * operates elementwise in 
NumPy arrays. 
The matrix product can be performed using the dot function or method:

In [5]:
A = np.array( [[1,1],[0,1]] )
print(A.shape)
B = np.array( [[2,0],[3,4]] )
print(B.shape)

(2, 2)
(2, 2)


In [6]:
print(A)
print(B)
A*B

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


array([[2, 0],
       [0, 4]])

In [8]:
A.dot(B) #matrix product

array([[5, 4],
       [3, 4]])

In [9]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing 
array rather than create a new one.

In [10]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))

In [11]:
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[ 0.88664845  0.04354423  0.85814776]
 [ 0.98977072  0.70397742  0.10227305]]


In [12]:
a *= 3 #equivalent to a=a*3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [14]:
b += a # equivalent to b=b+a
b

array([[ 6.88664845,  6.04354423,  6.85814776],
       [ 6.98977072,  6.70397742,  6.10227305]])

In [15]:
a += b  
# b is not automatically converted to integer type. cannot convert float to int

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

# Universal Functions

In [16]:
B = np.arange(3)

In [17]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [18]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [19]:
C = np.array([2., -1., 4.])

In [20]:
np.add(B, C)

array([ 2.,  0.,  6.])

In [21]:
np.all([[True,True],[True,True]])

True

In [21]:
np.all([[True,False],[True,True]], axis=0)


array([ True, False], dtype=bool)

In [22]:
np.all([[-1, 4, 8,7],[0,3,4,32]],axis=0)

array([False,  True,  True,  True], dtype=bool)

In [23]:
np.all([1.0, np.nan])

#Not a Number (NaN), positive infinity and negative infinity evaluate to True 
#because these are not equal to zero.

True

In [24]:
data = range(1,5)

In [25]:
np.average(data)

2.5

In [26]:
np.average(range(1,11), weights=range(10,0,-1))

4.0

In [27]:
data = np.arange(6).reshape((3,2))
print(data)
np.average(data, axis=1, weights=[1./4, 3./4])
#Axis must be specified when shapes of a and weights differ.

[[0 1]
 [2 3]
 [4 5]]


array([ 0.75,  2.75,  4.75])

In [29]:
x = np.array([[5,4], [9,9],[0,8]])
print(x)
np.nonzero(x)

[[5 4]
 [9 9]
 [0 8]]


(array([0, 0, 1, 1, 2], dtype=int64), array([0, 1, 0, 1, 1], dtype=int64))

In [31]:
x[np.nonzero(x)]

array([5, 4, 9, 9, 8])

In [32]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [2, 1]], dtype=int64)

A common use for nonzero is to find the indices of an array, where a condition 
is True. Given an array a, the condition a > 3 is a boolean array and since 
False is interpreted as 0, np.nonzero(a > 3) yields the indices of the a 
where the condition is true

In [33]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [48]:
(a > 3).nonzero()

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [46]:
def f(x,y):
    return 10*x+y

In [47]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [38]:
b[2,3]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [37]:
arr = np.arange(0,10)

In [38]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

D:\ana\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [42]:
# Also warning, but not an error instead infinity
1/arr

D:\ana\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111])

In [43]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [44]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [45]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [46]:
np.max(arr) #same as arr.max()

9

In [47]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [49]:
np.log(arr)

D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

In [50]:
a=float('nan')
type(a)

b=float('inf')

In [51]:
import math

In [52]:
math.isnan(a)

True

In [53]:
a=nan

NameError: name 'nan' is not defined