NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [1]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

In [3]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [4]:
for x in np.nditer(a):
    print (x, end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

In [5]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)

In [6]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [7]:
b = a.T # transposing an array

In [9]:
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [10]:
for x in np.nditer(b): 
    print (x,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

### Iteration order

In [12]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

b = a.T
print(a)
c = b.copy(order='C')

for x in np.nditer(c):
    print (x,end=" ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 20 40 5 25 45 10 30 50 15 35 55 

In [13]:
c = b.copy(order='F')

for x in np.nditer(c):
    print (x,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

It is possible to force nditer object to use a specific order by explicitly mentioning it.

In [14]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

In [15]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [16]:
#fancy indexing
a[[1,2,0],[1,2,3]] # [1,2,0] -->specifying which rows to consider
#[1,2,3] ----> specifying which columns to take

array([25, 50, 15])

In [18]:
for x in np.nditer(a, order = 'C'): 
    print (x,end=" ")  
print ('\n') 

print( 'Sorted in F-style order:' )
for x in np.nditer(a, order = 'F'): 
    print (x,end=" ") 

0 5 10 15 20 25 30 35 40 45 50 55 

Sorted in F-style order:
0 20 40 5 25 45 10 30 50 15 35 55 

In [29]:
a=np.arange(20).reshape(4,5)
for x in np.nditer(a):
    print(x,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [30]:
for x in np.nditer(a,order='F'):
    print(x,end=' ')

0 5 10 15 1 6 11 16 2 7 12 17 3 8 13 18 4 9 14 19 

In [31]:
b=np.copy(a)

In [32]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
for x in np.nditer(b,order='F'):
    print(x,end=' ')

0 5 10 15 1 6 11 16 2 7 12 17 3 8 13 18 4 9 14 19 

In [34]:
c=np.copy(a,order='F')

In [35]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
for x in np.nditer(c):
    print(x, end=' ')

0 5 10 15 1 6 11 16 2 7 12 17 3 8 13 18 4 9 14 19 