### Changing Shape

In [1]:
#reshape we have studied in other files

In [2]:
#flat --> A 1-D iterator over the array

In [3]:
import numpy as np 
a = np.arange(8).reshape(2,4) 
print ('The original array:' )
print (a) 
print ('\n') 

print ('After applying the flat function:' )
# returns element corresponding to index in flattened array 
print (a.flat[0:5])

The original array:
[[0 1 2 3]
 [4 5 6 7]]


After applying the flat function:
[0 1 2 3 4]


In [4]:
#Flatten

In [5]:
import numpy as np 
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a) 
print ('\n')  
# default is column-major 

print ('The flattened array is:') 
print (a.flatten() )
print ('\n')  

print ('The flattened array in F-style ordering:') 
print (a.flatten(order = 'F'))


The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The flattened array is:
[0 1 2 3 4 5 6 7]


The flattened array in F-style ordering:
[0 4 1 5 2 6 3 7]


In [6]:
#ravel

In [7]:
import numpy as np 
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a) 
print ('\n')  

print ('After applying ravel function:') 
print (a.ravel() ) 
print ('\n') 

print ('Applying ravel function in F-style ordering:') 
print (a.ravel(order = 'F'))

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


After applying ravel function:
[0 1 2 3 4 5 6 7]


Applying ravel function in F-style ordering:
[0 4 1 5 2 6 3 7]


### Transpose Operations

In [8]:
#transpose

In [9]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print ('The original array is:') 
print (a)  
print ('\n') 

print ('The transposed array is:') 
print (np.transpose(a))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [10]:
#ndarray.T

In [11]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print ('The original array is:') 
print (a) 
print ('\n')  

print ('Array after applying the function:' )
print (a.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array after applying the function:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Joining Arrays

In [12]:
#Concatenate

In [13]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:') 
print (np.concatenate((a,b))) # the first running vertically downwards across rows
print ('\n')  

print ('Joining the two arrays along axis 1:')
print (np.concatenate((a,b),axis = 1))#the second running horizontally across columns



First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [14]:
b=np.concatenate((a,b),axis = 1)

In [15]:
b.shape

(2, 4)

In [32]:
#stack

In [22]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])
print(a)
print('\n')
print(b)
print('\n')
print ('Stack the two arrays along axis 0:') 
print (np.stack((a,b),0) )
c=np.stack((a,b),0)
print(c.shape)
print('\n')
print ('Stack the two arrays along axis 1:') 
print (np.stack((a,b),1))



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [23]:
#hstack

In [25]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 

 
print (a)   
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
  
print('\n')
print ('Horizontal stacking:' )
c = np.hstack((a,b)) 
print (c )

d= np.vstack((a,b)) 
print (d )

[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Array spliting

In [42]:
#numpy.split(ary, indices_or_sections, axis)

In [39]:
import numpy as np 
a = np.arange(9) 

print (a) 
print('\n')
print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print (b)  
print('\n')
print ('Split the array at positions indicated in 1-D array:' )
b = np.split(a,[4])
print (b )
print('\n')
#np.array_split(b,2)

[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8])]




The numpy.hsplit is a special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array.

In [46]:
#numpy.hsplit

In [40]:
import numpy as np 
a = np.arange(16).reshape(4,4) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Horizontal splitting:' )
b = np.hsplit(a,2) 
print (b) 
print ('\n')
len(b)

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




2

In [49]:
#do vstack on ur own

### Adding/Removing Elements

In [50]:
#resize

In [53]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 

print (a.shape) 
print ('\n')  
b = np.resize(a, (3,2)) 

print ('Second array:' )
print (b) 
 

print (b.shape) 

# Observe that first row of a is repeated in b since size is bigger 

print ('Resize the second array:') 
b = np.resize(a,(3,3)) 
print (b)

b = np.resize(a,(4,4)) 
print('\n')
print (b)

First array:
[[1 2 3]
 [4 5 6]]
(2, 3)


Second array:
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
Resize the second array:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


[[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]
 [1 2 3 4]]


In [52]:
#append

In [53]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:' )
print (a) 
print ('\n'  )

print ('Append elements to array:') 
print (np.append(a, [7,8,9])) 
print ('\n')  

print ('Append elements along axis 0:') 
print (np.append(a, [[7,8,9]],axis = 0)) 
print ('\n')  

print ('Append elements along axis 1:') 
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [54]:
#unique

In [47]:
import numpy as np 
a = np.array([5,2,6,2,7,5,6,8,2,9]) 

print ('First array:') 
print (a )
  

print ('Unique values of first array:') 
u = np.unique(a) 
print( u )
print ('\n'  )

print ('Unique array and Indices array:' )
u,indices = np.unique(a, return_index = True) 
print (u,indices )
print ('\n')  

a[indices]

First array:
[5 2 6 2 7 5 6 8 2 9]
Unique values of first array:
[2 5 6 7 8 9]


Unique array and Indices array:
[2 5 6 7 8 9] [1 0 2 4 7 9]




array([2, 5, 6, 7, 8, 9])

In [50]:
print ('We can see each number corresponds to index in original array:' )
print (a) 
print ('\n')  

print ('Indices of unique array:' )
u,indices = np.unique(a,return_inverse = True) 
print (u,indices )
print ('\n' )

print ('Indices are:' )
print (u,indices )
print ('\n')  

print ('Reconstruct the original array using indices:') 
print (u[indices]) 
print ('\n' ) 

print ('Return the count of repetitions of unique elements:') 
u,indices = np.unique(a,return_counts = True) 
print (u )
print (indices)

We can see each number corresponds to index in original array:
[5 2 6 2 7 5 6 8 2 9]


Indices of unique array:
[2 5 6 7 8 9] [1 0 2 0 3 1 2 4 0 5]


Indices are:
[2 5 6 7 8 9] [1 0 2 0 3 1 2 4 0 5]


Reconstruct the original array using indices:
[5 2 6 2 7 5 6 8 2 9]


Return the count of repetitions of unique elements:
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [57]:
#delete
#Numpy.delete(arr, obj, axis)

In [58]:
import numpy as np 
a = np.arange(12).reshape(3,4) 

print( 'First array:' )
print (a) 
print ('\n'  )

print ('Array flattened before delete operation as axis not used:' )
print (np.delete(a,5)) 
print ('\n')  

print ('Column 2 deleted:'  )
print (np.delete(a,1,axis = 1) )
print ('\n' ) 

print ('A slice containing alternate values from array deleted:') 
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print (np.delete(a, np.s_[::2]))

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11]


Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


In [54]:
a=np.arange(10)

In [58]:
np.array_split(df,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]