### NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr=arr*2
#Get a value at an index
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr[1]

2

In [6]:
#Get values in a range
arr[1:5]

array([2, 4, 6, 8])

In [7]:
#Get values in a range
arr[0:5]

array([0, 2, 4, 6, 8])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [8]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [9]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
print(id(arr))
#Show
arr

835200064368


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Important notes on Slices
slice_of_arr = arr[0:6]
print(id(slice_of_arr))
#Show slice
slice_of_arr

835200063408


array([0, 1, 2, 3, 4, 5])

In [11]:
#Change Slice
slice_of_arr[:]=99
print(id(slice_of_arr))
#Show Slice again
slice_of_arr

835200063408


array([99, 99, 99, 99, 99, 99])

In [12]:
li = list(range(10))

In [13]:
new_li = li[:]

In [14]:
id(li), id(new_li)

(835200044616, 835200069704)

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

arr_copy[1:4]=2
print(arr_copy)

print(arr)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
#Indexing row
arr_2d[1,2]


30

In [18]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [20]:
# Getting individual element value
print(arr_2d[1,0])
arr_2d

20


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
# 2D array slicing
print(arr_2d)
#Shape (2,2) from top right corner
arr_2d[:2,1:]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [22]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [23]:
#Shape bottom row
arr_2d[2,:] # : basically means i want all the rows or columns

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [24]:
#Set up matrix
arr2d = np.zeros((10,10))
#print(arr2d)

In [25]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

10

In [26]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

Fancy indexing allows the following

In [27]:
arr2d[[9,3,4,3]]

array([[ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]])

In [30]:
arr2d[[2,4,6,8],[1,3,4,5]]

array([ 2.,  4.,  6.,  8.])

In [31]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [32]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
bool_arr = arr>4

In [36]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr = np.ones((3,4))

In [41]:
arr=arr[0] * 2

In [42]:
arr

array([ 2.,  2.,  2.,  2.])

In [ ]:
arr=np.arange(25).reshape(5,5)

In [ ]:
arr

In [ ]:
arr[[2,4,4],[1,3,4]]

In [ ]:
arr[[4,3,1]]

In [ ]:
arr[arr >= 5]